inherit_from: base/refinement_surface_reconstruction.yaml

nf: 12
unet_num_level: 5
layer_order: gcr
retrieval_fmaps: 12
retrieval_num_level: 4
attn_patch_extent: 4
attn_normalize: True
attn_use_switching: True
attn_retrieval_mode: True
attn_no_output_mapping: True
attn_blend: True
attn_num_patch: 16
num_workers: 8
disable_train_vis: True
disable_attn_vis: True

dataset:
  num_points: 500
  dataset_name: ShapeNetV2
  splits_dir: main
  voxel_size_input: 0
  voxel_size_target: 0.020834
  preload_scenes: False
  preload_retrievals: False
  target_mean: 0.059954833543534335
  target_std: 0.010110036361741626

dataset_train:
  train_multiplier: 1