inherit_from: base/retrieval_surface_reconstruction.yaml
dataset:
  dataset_name: 3DFront
  num_points: 500
  splits_dir: main
  voxel_size_input: 0
  voxel_size_target: 0.054167
  preload_scenes: True
  occupancy_threshold: 0
  target_mean: 0.15015658121788053
  target_std: 0.03573221820637578

retrieval_training:
  num_workers: 8
  batch_size: 256
  scheduler: [70, 80]

dictionary:
  batch_size: 256
  num_workers: 8

query:
  batch_size: 128
  num_workers: 8
  K: 1
  flann_num_workers: 4